apiVersion: apps/v1
kind: Deployment
metadata:
  name: servant-app
  labels:
    app: servant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servant-app
  template:
    metadata:
      labels:
        app: servant-app
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: servant-app
        image: priyan5hu24/servant-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
          
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cluster-secrets
              key: AWS_ACCESS_KEY
        
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cluster-secrets
              key: AWS_SECRET_KEY

        - name: BUCKET
          valueFrom:
            secretKeyRef:
              name: cluster-secrets
              key: BUCKET

        - name: INGEST_SERVICE_URL
          value: http://train-ingest-service:3333/train
        
        - name: TRAINER_SERVICE_URL
          value: http://train-trainer-service:4444/train

        - name: PUSHER_SERVICE_URL
          value: http://train-pusher-service:5555/train

---
apiVersion: v1
kind: Service
metadata:
  name: servant-app-service
spec:
  type: NodePort
  selector:
    app: servant-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000