name: CI Pipeline

# Trigger strictly on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    # Global environment variables mapping from GitHub Secrets
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      # Step 4: Automating the Training Pipeline using Github_Actions Server
      - name: Run Data_Ingestion
        env:
          BUCKET: ${{ secrets.BUCKET }}
        run: python trainer_mic1/Ingest/data_ingestion.py 

      - name: Run Model_Training
        env:
          BUCKET: ${{ secrets.BUCKET }}
        run: python trainer_mic1/train/model_trainer.py

      - name: Run Model_Pushing
        env:
          BUCKET: ${{ secrets.BUCKET }}
        run: python trainer_mic1/push/model_pusher.py 
  
  Continuous-Deployment:
    #using needs to prevent this job running before CI finishes.
    needs: Continuous-Integration 
    runs-on: self-hosted

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      BUCKET: ${{ secrets.BUCKET }}

    steps:
    
      # fetching only kube-menifests from the github instead of entire code base main main branch
      - name: Checkout Manifests Only
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            kube-menifests-deployment
          sparse-checkout-cone-mode: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # 1. Authenticate with Docker Hub (fixes pull rate limits & private image access)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. setup secrets.
      
      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic cluster-secrets \
                --from-literal=AWS_ACCESS_KEY=${{ env.AWS_ACCESS_KEY }} \
                --from-literal=AWS_SECRET_KEY=${{ env.AWS_SECRET_KEY }} \
                --from-literal=BUCKET=${{ env.BUCKET }} \
                --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Docker Registry Secret
        run: |
          kubectl create secret docker-registry dockerhub-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # 3. Apply all 4 Kubernetes manifests
      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f kube-menifests-deployment/ingest-menifest.yaml \
                        -f kube-menifests-deployment/trainer-menifest.yaml \
                        -f kube-menifests-deployment/pusher-menifest.yaml \
                        -f kube-menifests-deployment/servant-menifest.yaml

      # 4. Port forwarding to access app:
      
      - name : Accessing app using port-forwarding.
        run: |
          kubectl port-forward --address 0.0.0.0 svc/servant-app-service 5000:5000

      